### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by aseetharam** [ISUgenomics/bioinformatics-workbook#11]
as suggested by @hsiaoyi0504

**Comment by hsiaoyi0504** [comment]
For the installation part related to **jekyll**, it's Included in #10 and #12.

**Comment by aseetharam** [comment]
@hsiaoyi0504  feel free to use whatever the methods you want to commit/make changes. We will leave to the developers to select the method that is most suitable for them. Here at GIF, we are comfortable using Atom for writing and we find it very convenient for our purpose.  Please continue using jekyll/RubyGems, if it serves you well 👍 , we will, by no means force users to use one method over the other for contribution!

Our initial contribution guidelines is published [here](https://github.com/ISUgenomics/bioinformatics-workbook/blob/master/.github/contributing.md) and will be updated with more information soon. I'll close this issue for now and work on other pages in order to improve volunteer contribution experience. 

Thanks for bringing this to our attention,

The GIF team.

**Comment by hsiaoyi0504** [comment]
@aseetharam I know there are many means to develop, but the point here is to provide the possible methods to do that. The usage of **Atom** you mentioned is cool. However, it's not clear to new developer to start contributing the repo. Another thing is that without mentioning the library used such as **jekyll**, it's a hinder to start contribute.

The key difference between the **Atom** and the installation part I mentioned is that **Atom** is a code editor, but **jekyll** is the underlying library used for the web page.  It's not the choice of the editor. It's the native way to use **jekyll**.
